backend_opset_version = {
    'ATen': [],
    'Abs': [1, 6],
    'Acos': [],
    'Add': [1, 6],
    'Affine': [],
    'And': [1],
    'ArgMax': [1],
    'ArgMin': [1],
    'Asin': [],
    'Atan': [],
    'AveragePool': [1, 7],
    'BatchNormalization': [1, 6],
    'Cast': [1],
    'Ceil': [1, 6],
    'Clip': [1, 6],
    'Concat': [1, 4],
    'Constant': [1],
    'ConstantFill': [1],
    'Conv': [1],
    'ConvTranspose': [1],
    'Cos': [],
    'Crop': [],
    'DepthToSpace': [1],
    'Div': [1, 6],
    'Dropout': [1, 6],
    'Elu': [1, 6],
    'Equal': [1],
    'Exp': [1, 6],
    'Flatten': [1],
    'Floor': [1, 6],
    'GRU': [],
    'GRUUnit': [],
    'Gather': [1],
    'Gemm': [1, 6],
    'GivenTensorFill': [],
    'GlobalAveragePool': [1],
    'GlobalLpPool': [1, 2],
    'GlobalMaxPool': [1],
    'Greater': [1],
    'HardSigmoid': [1, 6],
    'Hardmax': [1],
    'Identity': [1],
    'If': [],
    'ImageScaler': [],
    'InstanceNormalization': [],
    'LRN': [1],
    'LSTM': [1],
    'LeakyRelu': [1, 6],
    'Less': [1],
    'Log': [1, 6],
    'LogSoftmax': [1],
    'Loop': [],
    'LoopIndexTensor': [],
    'LpNormalization': [1],
    'LpPool': [],
    'MatMul': [1],
    'Max': [1, 6],
    'MaxPool': [1],
    'MaxRoiPool': [],
    'Mean': [1, 6],
    'MeanVarianceNormalization': [],
    'Min': [1, 6],
    'Mul': [1, 6],
    'Neg': [1, 6],
    'Not': [1],
    'Or': [1],
    'PRelu': [1, 6],
    'Pad': [1, 2],
    'ParametricSoftplus': [],
    'Pow': [1],
    'RNN': [],
    'RandomNormal': [1],
    'RandomNormalLike': [1],
    'RandomUniform': [1],
    'RandomUniformLike': [1],
    'Reciprocal': [1, 6],
    'ReduceL1': [1],
    'ReduceL2': [],
    'ReduceLogSum': [1],
    'ReduceLogSumExp': [1],
    'ReduceMax': [1],
    'ReduceMean': [1],
    'ReduceMin': [1],
    'ReduceProd': [1],
    'ReduceSum': [1],
    'ReduceSumSquare': [1],
    'Relu': [1, 6],
    'Reshape': [1, 5],
    'Scale': [],
    'ScaledTanh': [],
    'Selu': [1, 6],
    'Shape': [1],
    'Sigmoid': [1, 6],
    'Sin': [],
    'Size': [1],
    'Slice': [1],
    'Softmax': [1],
    'Softplus': [1],
    'Softsign': [1],
    'SpaceToDepth': [1],
    'Split': [1, 2],
    'Sqrt': [1, 6],
    'Squeeze': [1],
    'Sub': [1, 6],
    'Sum': [1, 6],
    'Tan': [],
    'Tanh': [1, 6],
    'ThresholdedRelu': [1],
    'Tile': [1],
    'TopK': [1],
    'Transpose': [1],
    'Unsqueeze': [1],
    'Upsample': [1],
    'Xor': [1]
}

frontend_opset_version = {
    'ATen': [],
    'Abs': [1, 6],
    'Acos': [7],
    'Add': [1, 6],
    'Affine': [],
    'And': [1],
    'ArgMax': [1],
    'ArgMin': [1],
    'Asin': [7],
    'Atan': [7],
    'AveragePool': [1, 7],
    'BatchNormalization': [1, 6],
    'Cast': [1],
    'Ceil': [1, 6],
    'Clip': [],
    'Concat': [1, 4],
    'Constant': [],
    'ConstantFill': [1],
    'Conv': [1],
    'ConvTranspose': [],
    'Cos': [7],
    'Crop': [],
    'DepthToSpace': [],
    'Div': [1, 6],
    'Dropout': [],
    'Elu': [],
    'Equal': [],
    'Exp': [1, 6],
    'Flatten': [],
    'Floor': [1, 6],
    'GRU': [],
    'GRUUnit': [],
    'Gather': [],
    'Gemm': [],
    'GivenTensorFill': [],
    'GlobalAveragePool': [],
    'GlobalLpPool': [],
    'GlobalMaxPool': [],
    'Greater': [],
    'HardSigmoid': [],
    'Hardmax': [],
    'Identity': [],
    'If': [],
    'ImageScaler': [],
    'InstanceNormalization': [],
    'LRN': [],
    'LSTM': [],
    'LeakyRelu': [],
    'Less': [],
    'Log': [1, 6],
    'LogSoftmax': [1],
    'Loop': [],
    'LoopIndexTensor': [],
    'LpNormalization': [],
    'LpPool': [],
    'MatMul': [],
    'Max': [1, 6],
    'MaxPool': [1],
    'MaxRoiPool': [],
    'Mean': [],
    'MeanVarianceNormalization': [],
    'Min': [1, 6],
    'Mul': [1, 6],
    'Neg': [1, 6],
    'Not': [1],
    'Or': [1],
    'PRelu': [],
    'Pad': [1, 2],
    'ParametricSoftplus': [],
    'Pow': [1],
    'RNN': [],
    'RandomNormal': [1],
    'RandomNormalLike': [],
    'RandomUniform': [1],
    'RandomUniformLike': [],
    'Reciprocal': [1, 6],
    'ReduceL1': [],
    'ReduceL2': [],
    'ReduceLogSum': [],
    'ReduceLogSumExp': [],
    'ReduceMax': [1],
    'ReduceMean': [1],
    'ReduceMin': [1],
    'ReduceProd': [1],
    'ReduceSum': [1],
    'ReduceSumSquare': [],
    'Relu': [1, 6],
    'Reshape': [1, 5],
    'Scale': [],
    'ScaledTanh': [],
    'Selu': [1, 6],
    'Shape': [],
    'Sigmoid': [1, 6],
    'Sin': [7],
    'Size': [],
    'Slice': [],
    'Softmax': [1],
    'Softplus': [1],
    'Softsign': [1],
    'SpaceToDepth': [],
    'Split': [1, 2],
    'Sqrt': [1, 6],
    'Squeeze': [1],
    'Sub': [1, 6],
    'Sum': [1, 6],
    'Tan': [7],
    'Tanh': [1, 6],
    'ThresholdedRelu': [],
    'Tile': [1],
    'TopK': [1],
    'Transpose': [1],
    'Unsqueeze': [1],
    'Upsample': [],
    'Xor': [1]
}

frontend_tf_opset_version = {
    'Abs': [1, 6],
    'Acos': [7],
    'Add': [1, 6],
    'AddN': [1, 6],
    'ArgMax': [1],
    'ArgMin': [1],
    'Asin': [7],
    'Atan': [7],
    'AvgPool': [1, 7],
    'BatchNorm': [1, 6],
    'BiasAdd': [1, 6],
    'Cast': [1],
    'Ceil': [1, 6],
    'ConcatV2': [1, 4],
    'Conv1D': [1],
    'Conv2D': [1],
    'Conv3D': [1],
    'Cos': [7],
    'Exp': [1, 6],
    'ExpandDims': [1],
    'Fill': [1],
    'Floor': [1, 6],
    'FusedBatchNorm': [1, 6],
    'Log': [1, 6],
    'LogSoftmax': [1],
    'LogicalAnd': [1],
    'LogicalNot': [1],
    'LogicalOr': [1],
    'LogicalXor': [1],
    'Max': [1],
    'MaxPool': [1],
    'Maximun': [1, 6],
    'Mean': [1],
    'Min': [1],
    'Minimum': [1, 6],
    'Mul': [1, 6],
    'Neg': [1, 6],
    'Pad': [1, 2],
    'Pow': [1],
    'Prod': [1],
    'RandomStandardNormal': [1],
    'RandomUniform': [1],
    'RealDiv': [1, 6],
    'Reciprocal': [1, 6],
    'Relu': [1, 6],
    'Reshape': [1, 5],
    'Selu': [1, 6],
    'Sigmoid': [1, 6],
    'Sin': [7],
    'Softmax': [1],
    'Softplus': [1],
    'Softsign': [1],
    'SplitV': [1, 2],
    'Sqrt': [1, 6],
    'Squeeze': [1],
    'Sub': [1, 6],
    'Sum': [1],
    'Tan': [7],
    'Tanh': [1, 6],
    'Tile': [1],
    'TopKV2': [1],
    'Transpose': [1]
}
